### ISSUE TITLE
Actualizar requisitos para pasar los test: Práctica 1

### ISSUE THREAD

**Issue by LeandroVP** [JJ/IV#106]
Es necesario tener creados al menos tres hitos para pasar el test. En la documentación se dice _Uso de milestones/issues para añadir siempre código al repositorio_ pero no se especifica el número de hitos que deben estar ya creados en el momento de entregar.

**Comment by JJ** [comment]
Como hemos explicado en el grupo de Telegram, es un detalle de
implementación. El estudiante debe decidir cuantos son "suficientes", se
comenta en clase, y si eso no es suficiente, el test te dice cuantos son.

**Comment by LeandroVP** [comment]
Según el documento de la primera práctica, "_En este caso, el hito será la entrega de la práctica y las órdenes de trabajo las diferentes tareas necesarias para terminar el hito._". Por lo tanto, ¿qué sentido tiene que sean tres hitos y que se tenga que "decidir"? Si hay que hacerlos todos desde el principio, debería hacer 8; o si fuera siguiendo la asignatura semana a semana, de uno en uno... ¿No pueden estar los requisitos más claros desde el principio?

**Comment by JJ** [comment]
En la descripción del documento pone

> Se trata de pensar o elegir un proyecto que se irá elaborando durante el año, creando los hitos para organizar el trabajo en el mismo. 

Una vez más, el clase se dice (y se puede ver en la web de la asignatura) que generalmente habrá 6-7 hitos. 3, sin embargo, es el mínimo porque, al menos, habrá que poner el propio hito (el 1) y los dos siguientes (si no se quiere poner los del resto del año). 
Además, ¿hay una forma más clara de poner los requisitos que en un test? Nuestro objetivo no es que se envíe bien desde el principio, es que no se fusione a menos que esté bien.

**Comment by LeandroVP** [comment]
Por qué los "dos siguientes"? Lo que quiero entender es por qué no está "bien" que me plantee únicamente mi próximo hito y, una vez lo alcance, el siguiente.

Además, si se dice textualmente que _Como mínimo, y para pasar los tests, esta entrega incluirá..._ y luego resulta que realmente hay más cosas que cumplir, seguramente se deba cambiar algo.

**Comment by JJ** [comment]
@LeandroVP Si así lo justificas en tu PR, se puede mergear sin pasar ese test. Como tú dices, dice como mínimo. Adicionalmente, necesita que pase ese test también. Y el hecho de que no ponga dos, o tres, o cuatro, es porque el objetivo del hito no es que pongáis 2, o 3, o 4 milestones. Es que describáis la estructura del proyecto en los milestones. Es muy posible que tu proyecto en particular necesite sólo 2. En general, y como está estructurada la asignatura, va a necesitar al menos tres. Como he dicho, son detalles de implementación *que comentamos en clase* y que *están en el test* con mayor transparencia imposible. Pero insisto, dado que es un detalle de implementación, estamos dispuestos a escuchar razones por las que imprescindiblemente sólo se puedan tener 2 hitos ahora mismo y por tanto a mergear el PR correspondiente. El guión se queda como está, agradeciéndote de todas formas tu aportación.

**Comment by LeandroVP** [comment]
Considero entonces aclarado el "por qué" se ha elegido que sean 3. Sin embargo, le pido que tenga en cuenta que el motivo de la apertura de este issue no es cambiar los tests o el contenido de estos, sino corregir la contradicción generada por _Como mínimo, y **para pasar los tests**, esta entrega incluirá..._ y el hecho de que a pesar de que un proyecto cumpla los apartados descritos, no los pase. Muchas gracias por responder tan detalladamente.
