### ISSUE TITLE
Documentar como se genera la página de la asignatura 

### ISSUE THREAD

**Issue by antoniogamiz** [JJ/IV#115]
He intentado resolver #114, pero no sé qué se usa para generar la página.

**Comment by lulivi** [comment]
las paginas de jj.github.io/IV se generan automáticamente al hacer un push en la rama de gh-pages. Internamente se usa jekyll creo. Puedes probar [esto](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/testing-your-github-pages-site-locally-with-jekyll#step-4-build-your-local-jekyll-site) para ejecutarlas en local.

**Comment by lulivi** [comment]
Si lo que quieres saber es como se sincronizan los commits automáticamente entre master y gh-pages (#114) se utiliza [este script](https://github.com/JJ/IV/blob/master/app/git-hooks.pl) como hook de git

**Comment by JJ** [comment]
Gracias, @lulivi , por explicarlo; lo he aclarado un poco mejor en tu issue #114; cierro en todo caso este en favor de aquél, ya que si se genera automáticamente, no será necesario documentarlo.
