### ISSUE TITLE
Los tests no detectan de forma correcta issues cerrados en PR

### ISSUE THREAD

**Issue by yabirgb** [JJ/IV#122]
En mi proyecto para trabajar en algunos issues he decidido trabajar con ramas que luego he mergeado en la rama master utilizando una pull-request de github. Los commits de estas pull-requests cerraban tres issues como se puede comprobar en 

- https://github.com/yabirgb/bukhgalter/issues/22
- https://github.com/yabirgb/bukhgalter/issues/20
- https://github.com/yabirgb/bukhgalter/issues/16

Estas PR han sido mergeadas y los issues se han cerrado correctamente pero los tests de github actions no lo detectan así 

https://github.com/JJ/IV-20-21/pull/365/checks?check_run_id=1260149601

**Comment by yabirgb** [comment]
Como documentación adicional decir que en la API de github si aparece el `commit_id` https://github.com/yabirgb/IV-20-21/runs/1260381710?check_suite_focus=true#step:3:561 por lo que no entiendo por qué el test falla

**Comment by JJ** [comment]
@yabirgb El problema es que ese commit_id no es nulo sólo cuando se cierra desde un commit. Es nulo cuando se cierra desde un PR. Para este y solucionar el problema de @CeciMerelo, que tenía el mismo problema, hice una ñapa. Esa ñapa no funciona en tu caso. Puedo intentar hacer otra ñapa o hacer como dice el que me contestó en StackOverflow, meterme en GraphQL. Si es ñapa, seguramente podré tenerlo para mañana. Si es GraphQL, va a tener que esperar un poquito.

**Comment by yabirgb** [comment]
Yo he llegado a que el evento anterior queda como referenciado. Estoy viendo si se puede seguir la referencia y ver que se cierra en la pr

**Comment by JJ** [comment]
@yabirgb A ver, eso tiene que suceder no matter what. Porque tienes que referenciar el issue de alguna forma. El problema es que es posible que no sea justo el anterior. Y en todo caso será otra ñapa.

**Comment by JJ** [comment]
@JJ Es decir, lo que haría sería listar los eventos de ese issue y mirar a ver qué hay que lo haga "especial".  Pero igual no hay nada y al final tengo que usar GraphQL no matter what.
