### ISSUE TITLE
Duda sobre la rúbrica 3 del Hito-5

### ISSUE THREAD

**Issue by guillelpnz** [JJ/IV#135]
La rúbrica es esta:
2 puntos: uso (e integración) de varias plataformas de despliegue (es decir, no repetir la misma función en todas las plataformas, sino crear funciones nuevas que también se integren en el proyecto). o uso de plataformas tales como Firebase o Azure functions.

La duda:
¿Con uso e integración se refiere a tener alojada una función de nuestro proyecto que funcione, o bastaría con haber probado estas plataformas? Aunque no hayan funcionado finalmente

**Comment by JJ** [comment]
No, no basta con haber probado, eso lo dije en la clase donde presenté esto
y está grabado. No está mal aclararlo aquí, supongo.
