### ISSUE TITLE
Aclarar POST y GET en el tema REST otro año

### ISSUE THREAD

**Issue by guillelpnz** [JJ/IV#136]

**Comment by JJ** [comment]
¿Puedes ampliar un poco más lo que quieres que se aclare, por favor? ¿Quizás te refieres a que hay que explicar las partes de un URL y cómo se pueden usar para codificar parámetros?

**Comment by guillelpnz** [comment]
A eso mismo me refiero. Y si se pudiera dar un ejemplo de procesamiento de peticiones GET/POST en algún lenguaje

**Comment by JJ** [comment]
Cierto, debería añadirse. Muchas gracias por indicarlo.
