### ISSUE TITLE
Evitar el cierre del API debido a demasiadas peticiones

### ISSUE THREAD

**Issue by Davidspace** [JJ/IV#139]
El error en cuestión sucede cuando, como es el caso de mi repo, se intenta pasar los tests de GitHub Actions a un repositorio con, parece ser, demasiados issues. Esto activa un mecanismo de prevención del abuso que sería recomendable evitar.

**Comment by JJ** [comment]
¿Puedes enlazarlo, por favor? Gracias por el issue.

**Comment by Davidspace** [comment]
Se trata del test closing_issue_check: https://github.com/JJ/IV-20-21/runs/1457797967
