### ISSUE TITLE
Enlace erroneo sitio web LXC

### ISSUE THREAD

**Issue by mabarrbai** [JJ/IV#18]
En el tema de contenedores, el enlace del sitio web de LXC del ejercicio 1 dirige a linuxcontainers.com el cual no existe. La URL correcta es linuxcontainers.org

**Comment by JJ** [comment]
Te agradecería un pull request.

2015-11-25 17:51 GMT+01:00 Manuel Alejandro Barranco Bailón <
notifications@github.com>:

> En el tema de contenedores, el enlace del sitio web de LXC del ejercicio 1
> dirige a linuxcontainers.com el cual no existe. La URL correcta es
> linuxcontainers.org
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JJ/IV/issues/18>.
>



-- 
JJ
