### ISSUE TITLE
Enlaces rotos "Fichero objetivo X"

### ISSUE THREAD

**Issue by eantoniocalo18** [JJ/IV#183]
Se ha observado que hay varios enlaces rotos en los guiones de varios objetivos http://jj.github.io/IV/documentos/proyecto/*

**Comment by eantoniocalo18** [comment]
Tras revisar el código y los PR anteriores he comprobado que el problema ha sido corregido por otros compañeros.
Sin embargo, al acceder a las páginas:
https://jj.github.io/IV/documentos/proyecto/4.Tests

**Comment by JJ** [comment]
Cierto, tengo que regenerarlas. Gracias por avisar.
