### ISSUE TITLE
Considerar Github Projects como herramienta de gestión 

### ISSUE THREAD

**Issue by Asmilex** [JJ/IV#189]
[Github Projects](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/about-projects) (en beta actualmente) podría ser una herramienta muy potente para la asignatura.

Permitiría a los estudiantes organizarse mejor, viendo el estado general del repositorio. Además, creo que tiene integración con los Actions, pero esto no lo he comprobado personalmente. 

Ejemplos de uso: 

- Ver los correctores asignados a un PR.
- Visualizar rápidamente las fechas estimadas de los objetivos. 
- Comprobar en qué objetivos se encuentran el resto de compañeros. 
- Etiquetas de ayuda para los alumnos (Ejemplo: persona está atascada en issue. Añade una etiqueta a su issue/PR. El resto de estudiantes lo visualiza, y alguien podría decidir entrar a ayudar. Lo que suele ocurrir por Telegram, pero formalizado).

**Comment by JJ** [comment]
Pero te refieres a explicar a los estudiantes como usarlo en su propio proyecto, ¿correcto?

**Comment by Asmilex** [comment]
Tenía en mente usarlo para la asignatura en sí, más que para cada proyecto individual. De todas formas te permite añadir issues y PRs de repositorios diferentes, así que parece bastante conveniente.

**Comment by JJ** [comment]
Estoy poniendo unas pruebas [aquí](https://github.com/users/JJ/projects/2/views/1) Como no lo he usado, no tengo muy claro cómo usarlo y la utilidad que puede tener. Si se pueden añadir automáticamente los PRs de los estudiantes agrupados por objetivo, puede ser útil para dar una visión mejor que la vista cronológica de la lista de PRs.

**Comment by JJ** [comment]
Anda, si tiene una github action y todo... https://github.com/actions/add-to-project

**Comment by JJ** [comment]
Te agradezco el issue, pero tras contemplarlo el año pasado, no veo una forma sencilla de incorporarlo o a los flujos de la asignatura, o explicárselo a los estudiantes. Añade algo de complejidad, y la verdad es que en la mayoría de los casos trabajar con issues y milestones es más que suficiente. :pray: en todo caso.
