### ISSUE TITLE
Error en enlace a la lista de correo

### ISSUE THREAD

**Issue by manuasir** [JJ/IV#29]
Hace referencia al grupo del curso 2015

**Comment by JJ** [comment]
Este curso tiene mogollón de ficheros. No sé de qué fichero me estás hablando. Por favor, inscríbete en hacktoberfest, y a partir de ahí, quién mejor que tú para corregirlo y hacer un pull request.. Desde el commit que hagas puedes poner "closes #29" para cerrarlo una vez admitido.
