### ISSUE TITLE
Valoración de la implementación de la interfaz REST

### ISSUE THREAD

**Issue by juanjetomas** [JJ/IV#39]
En el [guión del hito 3](https://github.com/JJ/IV/blob/master/documentos/proyecto/3.PaaS.md) indica que como objetivo secundario es la implementación de la interfaz REST. He realizado dicha implementación y el testeo correspondiente pero no tengo claro en qué apartado se puntúa dicho objetivo o si ni siquiera puntúa.

**Comment by JJ** [comment]
El 22 de noviembre de 2016, 9:18, Juan Jesús Tomás Rojas <
notifications@github.com> escribió:

> En el guión del hito 3
> <https://github.com/JJ/IV/blob/master/documentos/proyecto/3.PaaS.md>
> indica que como objetivo secundario es la implementación de la interfaz
> REST. He realizado dicha implementación y el testeo correspondiente pero no
> tengo claro en qué apartado se puntúa dicho objetivo o si ni siquiera
> puntúa.
>

Realmente, no se dice eso. El objetivo viene a decir que este tipo de
aplicaciones basados en marcos como Rails es lo que se usa hoy en día, en
vez de aplicaciones basadas en servidores de propósito general y que se
pretende que al desplegarlos en PaaS se aprende a hacer ese tipo de cosas.

Cualquier avance en la implementación se valora, pero en los "puntos
adicionales".

**Comment by juanjetomas** [comment]
En puntos adicionales yo tengo un 0, ¿la interfaz REST de la que hablamos no me cuenta nada como avance en la implementación?

**Comment by JJ** [comment]
Puedes tener un 0 por diferentes razones, inclusive haber enviado tarde. Y si la implementación de la que hablas no estaba bien clarita en el README.md, es difícil valorarla. Si lo has puesto correctamente en el README.md, lo reviso y te digo.

**Comment by juanjetomas** [comment]
En el archivo [README.md](https://github.com/juanjetomas/ProyectoIV/blob/master/README.md) de mi proyecto figura un apartado llamado [Interfaz REST](https://github.com/juanjetomas/ProyectoIV/blob/master/README.md#interfaz-rest) donde se menciona dicha implementación y se hace referencia a la documentación donde se explica con más detalle.
