### ISSUE TITLE
Tema gestión de configuraciones: Vagrant. Problemas con el plugin libvirt

### ISSUE THREAD

**Issue by jojelupipa** [JJ/IV#75]
Siguiendo las instrucciones del profesor se ha instalado la versión descargable en la [página de vagrant](https://www.vagrantup.com/downloads.html) en lugar de la instalada por el gestor de paquetes de mi distribución (apt).

Esto ha desembocado en que máquinas que había probado con la versión de apt dejasen de funcionar al probar la versión de la página de vagrant. El problema estaba en el plugin de vagrant **libvirt**.

Al intentar “lanzar” la máquina con `vagrant up` devolvía el siguiente error:

```
>$ vagrant up 
The provider 'libvirt' could not be found, but was requested to
back the machine 'default'. Please use a provider that exists.

Vagrant knows about the following providers: virtualbox, hyperv, docker
``` 

Lo cual sugería que faltaba dicho elemento. He probado a instalarlo con `vagrant plugin install libvirt` pero devuelve un problema de dependencias:

```
>$ vagrant plugin install libvirt
Installing the 'libvirt' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

conflicting dependencies ffi (~> 0.6.3) and ffi (= 1.9.25)
  Activated ffi-1.9.25
  which does not match conflicting dependency (~> 0.6.3)

  Conflicting dependency chains:
    ffi (= 1.9.25), 1.9.25 activated

  versus:
    libvirt (> 0), 0.1.0 activated, depends on
    ffi (~> 0.6.3)
```

Por lo cual no he podido comprobar si el problema es del plugin en sí, [que está algo desactualizado](https://github.com/vagrant-libvirt/vagrant-libvirt) y por tanto debería buscar alguna [vagrantbox](https://www.vagrantbox.es/) que no requiera de este plugin, pero entre enlaces rotos y problemas de almacenamiento no he encontrado si esto es una solución.

Si en algún momento encuentro algo de información al respecto lo iré añadiendo aquí.

**Comment by JJ** [comment]
OK, muchas gracias. Creo que lo eliminaré de los apuntes.

**Comment by jojelupipa** [comment]
Actualización:

Me he dado cuenta de que el proveedor que estaba usando para la vagrantbox era virtualbox. Pero aun así me daba error y decía que era porque la máquina por defecto estaba asociada a “libvirt” así que sospeché que sería algún archivo de configuración residual que se habría quedado al lanzar otra máquina que sí que usaba libvirt.

Así que efectivamente era fallo mío. La configuración que había en el directorio `.vagrant` estaba dando problemas.

Así que a modo de conclusión: No se debería usar libvirt con versiones actuales de vagrant y no se debería utilizar un mismo directorio para instalar VM de distintos proveedores si no se “limpia” todo el directorio muy bien antes.
